### List

In [1]:
# List of any Datatypes. Here String and int
list1 = ['k',1,4,8]     
list2 = ['satya',9,45,30]

In [2]:
list1

['k', 1, 4, 8]

In [3]:
np.array(['k',1,4,8])

<IPython.core.display.Javascript object>

array(['k', '1', '4', '8'], dtype='<U1')

In [4]:
np.array([['k',1,4,8],['satya',9,45,30]])

<IPython.core.display.Javascript object>

array([['k', '1', '4', '8'],
       ['satya', '9', '45', '30']], dtype='<U5')

In [5]:
np.array(list1)

<IPython.core.display.Javascript object>

array(['k', '1', '4', '8'], dtype='<U1')

In [6]:
np.array(list2)

<IPython.core.display.Javascript object>

array(['satya', '9', '45', '30'], dtype='<U5')

In [7]:
np.add(list1,list2)

<IPython.core.display.Javascript object>

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U5'), dtype('<U5')) -> dtype('<U5')

In [8]:
np.array([list1,list2])

<IPython.core.display.Javascript object>

array([['k', '1', '4', '8'],
       ['satya', '9', '45', '30']], dtype='<U5')

### Array

In [9]:
# Array of Same Datatype. Here int
arr1 = [1,4,8]
arr2 = [9,45,30]

In [10]:
arr1

[1, 4, 8]

In [11]:
np.array([[1,4,8],[9,45,30]])

<IPython.core.display.Javascript object>

array([[ 1,  4,  8],
       [ 9, 45, 30]])

In [12]:
np.array([1,4,8])

<IPython.core.display.Javascript object>

array([1, 4, 8])

In [13]:
np.array(arr1)

<IPython.core.display.Javascript object>

array([1, 4, 8])

In [14]:
np.array(arr2)

<IPython.core.display.Javascript object>

array([ 9, 45, 30])

In [15]:
np.add(arr1,arr2)

<IPython.core.display.Javascript object>

array([10, 49, 38])

In [16]:
np.array([arr1,arr2])

<IPython.core.display.Javascript object>

array([[ 1,  4,  8],
       [ 9, 45, 30]])

In [17]:
### Array using Tuples
np.array([(1,2,3),(4,5,6),(7,8,9)])

<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Series 
- One Dimensional
- Column in a Excel File

##### Lists

In [18]:
pd.Series([1,2,3])

<IPython.core.display.Javascript object>

0    1
1    2
2    3
dtype: int64

In [19]:
pd.Series([[1,2,3],[4,5,6],[7,8,9]])

<IPython.core.display.Javascript object>

0    [1, 2, 3]
1    [4, 5, 6]
2    [7, 8, 9]
dtype: object

##### Arrays

In [20]:
pd.Series(np.array([1,2,3]))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

0    1
1    2
2    3
dtype: int32

In [21]:
pd.Series(np.array([[1,2,3],[4,5,6]]))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Exception: Data must be 1-dimensional

##### Dictionaries

In [ ]:
pd.Series({'English':[1,2,3],'Maths':[4,5,6],'Telugu':[7,8,9]})

In [22]:
{'English':[1,2,3],'Maths':[4,5,6],'Telugu':[7,8,9]}

{'English': [1, 2, 3], 'Maths': [4, 5, 6], 'Telugu': [7, 8, 9]}

## DataFrames

In [23]:
# Arrays
pd.DataFrame(np.array([[1,4,7],[2,5,8],[3,6,9]]))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [24]:
# Dictionaries
pd.DataFrame({'English':[1,2,3],'Maths':[4,5,6],'Telugu':[7,8,9]})

<IPython.core.display.Javascript object>

English  Maths  Telugu
0        1      4       7
1        2      5       8
2        3      6       9

In [25]:
pd.DataFrame({'English':pd.Series([1,2,3]),'Maths':pd.Series([4,5,6]),'Telugu':pd.Series([7,8,9])})

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

English  Maths  Telugu
0        1      4       7
1        2      5       8
2        3      6       9